linters-settings:
  gofmt:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  testifylint:
  wrapcheck:

linters:
  enable:
    - gofmt
    - revive
    - testifylint
    - wrapcheck

issues:
  include:
    - EXC0012 # EXC0012 revive: Annoying issue about not having a comment. The rare codebase has such comments
    - EXC0014 # EXC0014 revive: Annoying issue about not having a comment. The rare codebase has such comments
