version: "3"

services:
  app:
    build:
      context: .

    command: sh -c "make test"

    links:
      - mysql
      - postgresql
      - oracle

    environment:
      # TEST_ARGS: -v
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: plant_erd_test
      POSTGRES_HOST: postgresql
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: plant_erd_test
      ORACLE_SYSTEM_PASSWORD: oracle
      ORACLE_HOST: oracle
      ORACLE_USER: system
      ORACLE_PASSWORD: oracle
      ORACLE_PORT: 1521
      ORACLE_SERVICE: xe
      LD_LIBRARY_PATH: /opt/oracle/instantclient
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig/
      NLS_LANG: AMERICAN_AMERICA.UTF8

    volumes:
      - go-mod:/go/pkg/mod

  mysql:
    image: mysql:8

    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: plant_erd_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"

  postgresql:
    image: postgres:12-alpine

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: plant_erd_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  oracle:
    image: deepdiver/docker-oracle-xe-11g:2.0

    ports:
      - 1521:1521

    environment:
      ORACLE_SYSTEM_PASSWORD: oracle

volumes:
  go-mod:
    driver: local
